# Generated by Django 2.1.5 on 2019-02-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='AliasDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AliasDomains',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quota', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.Domain')),
            ],
            options={
                'verbose_name_plural': 'Mailboxes',
            },
        ),
        migrations.CreateModel(
            name='TLSPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(blank=True, choices=[('may', 'may'), ('encrypt', 'encrypt'), ('dane', 'dane'), ('dane-only', 'dane-only'), ('fingerprint', 'fingerprint'), ('verify', 'verify'), ('secure', 'secure')], max_length=20)),
                ('params', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'TLS Policy',
                'verbose_name_plural': 'TLS Policies',
            },
        ),
        migrations.AddField(
            model_name='aliasdomain',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.Domain'),
        ),
        migrations.AddField(
            model_name='alias',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.Domain'),
        ),
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together={('name', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('name', 'domain')},
        ),
    ]
